"""Default topic seeds for query generation (STEM / CS / ML education slant)."""

# One-line topic phrases; combined with templates in querygen.py to reach large N.
TOPICS: list[str] = [
    "binary search",
    "hash tables",
    "linked lists vs arrays",
    "Big-O notation",
    "recursion and the call stack",
    "dynamic programming basics",
    "graph breadth-first search",
    "graph depth-first search",
    "Dijkstra shortest path",
    "topological sort",
    "union-find (disjoint sets)",
    "heaps and priority queues",
    "tries (prefix trees)",
    "Bloom filters",
    "consistent hashing",
    "the CAP theorem",
    "ACID vs BASE in databases",
    "B-trees and LSM-trees",
    "vector clocks",
    "the Two Generals problem",
    "the Byzantine Generals problem",
    "Raft consensus (high level)",
    "Paxos intuition",
    "leader election",
    "quorum reads and writes",
    "MapReduce",
    "Spark lineage",
    "data skew in joins",
    "the transformer architecture",
    "self-attention",
    "positional encodings",
    "layer normalization",
    "residual connections",
    "tokenization for LLMs",
    "LoRA fine-tuning (conceptual)",
    "RLHF overview",
    "gradient descent",
    "stochastic gradient descent",
    "momentum and Adam",
    "backpropagation intuition",
    "convolutional neural networks",
    "overfitting vs underfitting",
    "bias-variance tradeoff",
    "cross-entropy loss",
    "softmax",
    "the kernel trick in SVMs",
    "k-means clustering",
    "PCA dimensionality reduction",
    "eigenvectors and eigenvalues (visual)",
    "singular value decomposition (intuition)",
    "Markov chains",
    "hidden Markov models (overview)",
    "Bayes theorem with a simple example",
    "maximum likelihood estimation",
    "the central limit theorem (intuition)",
    "confidence intervals",
    "p-hacking and multiple comparisons",
    "regular expressions basics",
    "finite automata",
    "pushdown automata (idea)",
    "Turing machines (toy example)",
    "the halting problem (lay explanation)",
    "NP vs P (informal)",
    "reductions in complexity",
    "memoization vs tabulation",
    "tail recursion",
    "garbage collection basics",
    "reference counting vs tracing GC",
    "virtual memory and paging",
    "CPU caches and locality",
    "pipelining in CPUs",
    "branch prediction",
    "mutexes vs semaphores",
    "deadlock and the dining philosophers",
    "livelock and starvation",
    "compare-and-swap",
    "memory ordering (high level)",
    "TCP vs UDP",
    "the TCP handshake",
    "sliding window flow control",
    "DNS resolution",
    "TLS handshake (simplified)",
    "HTTP/2 multiplexing",
    "REST vs GraphQL (when to use)",
    "idempotency in APIs",
    "JWT structure (no crypto deep dive)",
    "OAuth2 roles (conceptual)",
    "symmetric vs asymmetric encryption",
    "diffie-hellman key exchange (idea)",
    "zero-knowledge proofs (cartoon level)",
    "blockchain ledger basics",
    "Merkle trees",
    "Git commits as a DAG",
    "merge vs rebase (conceptual)",
    "semantic versioning",
    "feature flags",
    "blue-green deployments",
    "canary releases",
    "SLIs SLOs and error budgets",
    "histograms vs summaries for latency",
    "distributed tracing spans",
    "structured logging fields",
    "unit vs integration tests",
    "property-based testing idea",
    "mutation testing (overview)",
    "fuzzing basics",
    "static analysis vs dynamic analysis",
    "type systems: nominal vs structural",
    "algebraic data types",
    "monads as burritos (gentle)",
    "functors and maps",
    "lazy evaluation",
    "tail-call optimization",
    "continuations (intuition)",
    "event loops in async runtimes",
    "promises vs futures",
    "backpressure in streams",
    "circuit breakers",
    "retry with exponential backoff",
    "bulkhead pattern",
    "rate limiting token bucket",
    "sharding strategies",
    "consistent reads in distributed DBs",
    "vector databases and ANN search",
    "embedding spaces",
    "RAG pipeline overview",
    "prompt injection risks (high level)",
    "evals for LLM apps",
    "Manim Scene vs ThreeDScene",
    "animating a number line",
    "VGroup layout tips",
    "LaTeX in Manim (MathTex)",
]
